# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ecd2a9ab63dc23cffe2b1733afd6d5bbfef7a7c0e279508644f8cb55299174439821fb895004184de914234b4129f3e18df8064cc2ce927c05bd569756ffc90

test:
  secret_key_base: d74fff8783a995a28a15c42f220948ff8b2a24beac177b3fccbb9ff0717f3e5003ea6fea1e7892231cb6bc01f94e99db0896f6469f92e67f5f3dfd419c90587a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
